name: beer_counter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # firebase stuff
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  firebase_database: 3.1.6
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.4.4
  # to access geo location
  geolocator: ^5.3.2+2
  # picker
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  # map
  flutter_map: any
  latlong: any
  flutter_svg: any

  flutter_launcher_icons: ^0.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

# specify launcher icons
flutter_icons:
  image_path_android: "assets/ic_launcher_android.png"
  android: true # can specify file name here e.g. "ic_launcher"
  image_path_ios: "assets/ic_launcher_ios.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # android adaptive icons only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"
